version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/sentient1
      - DIALOGUE_VAE_ENDPOINT=http://vae-service:8000
      - TENSORFLOW_ENDPOINT=http://ml-server:5000/tensorflow
      - PYTORCH_ENDPOINT=http://ml-server:5000/pytorch
      - ENABLE_CONTINUOUS_LEARNING=true
      - ENABLE_AUTONOMOUS_DEBUGGING=true
      - ENABLE_ETHICAL_FILTERING=false
    depends_on:
      - mongodb
      - vae-service
      - ml-server
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
    restart: unless-stopped

  vae-service:
    build:
      context: .
      dockerfile: Dockerfile.vae
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/dialogue-vae
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  ml-server:
    build:
      context: .
      dockerfile: Dockerfile.ml-server
    ports:
      - "5000:5000"
    environment:
      - MODEL_DIR=/app/models
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  file-processor:
    build:
      context: .
      dockerfile: Dockerfile.file-processor
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  mongodb_data:
